name: Build

on:
  push:
    branches: ["**"]
    paths:
      - 'ImageCoverExpander/**'
      - '.github/workflows/main.yml'
  pull_request:
    branches: ["**"]
    paths:
      - 'ImageCoverExpander/**'
      - '.github/workflows/main.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: 3.1.x
      - name: GetStrippedRefs
        env:
          FILES_URL: ${{ secrets.BSFILES_URL }}
        run: wget --no-check-certificate "$FILES_URL" -q -O bsfiles.zip
      - name: ExtractRefs
        run: unzip -q -n bsfiles.zip -d ./Refs
      - name: Build
        id: Build
        env:
          FrameworkPathOverride: /usr/lib/mono/4.8-api
        run: dotnet build --configuration Release
      - name: Echo Filename
        run: echo "$BUILDTEXT ($ASSEMBLYNAME)"
        env:
          BUILDTEXT: Filename=${{ steps.Build.outputs.filename }}
          ASSEMBLYNAME: AssemblyName=${{ steps.Build.outputs.assemblyname }}
      - name: Upload Plugin Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.Build.outputs.filename }}
          path: ${{ steps.Build.outputs.artifactpath }}